# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_badge_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_badge_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
