# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='default/Default_avatar.jpg', upload_to='user/avatar/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='year_of_graduation',
            field=models.IntegerField(choices=[(2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2018, verbose_name='year'),
        ),
    ]
