# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20180809_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='log.UserProfile'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_user', to='log.UserProfile'),
        ),
    ]
