# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_userprofile_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.CharField(choices=[('none', 'none'), ('codeschool', 'codeschool'), ('cogitans', 'cogitans'), ('ecell', 'ecell'), ('electrotech', 'electrotech'), ('oslc', 'oslc'), ('renderedusict', 'renderedusict'), ('turingai', 'turingai'), ('techspace', 'techspace')], default='none', max_length=255),
        ),
    ]
