# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comments_reply_for'),
        ('log', '0002_auto_20180812_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like_notification', 'like_notification'), ('comment_notification', 'comment_notification'), ('message_notification', 'message_notification')], max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti', to='log.Message')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='log.UserProfile')),
            ],
        ),
    ]
