# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20180722_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.URLField(blank=True),
        ),
    ]
