# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 12:07
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
