# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20180816_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
