# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170911_1838'),
        ('log', '0007_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='club',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(to='home.Club'),
        ),
    ]
