# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20180816_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_activated',
            field=models.BooleanField(default=False),
        ),
    ]
