# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20180727_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='u',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=255),
        ),
    ]
