# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20180727_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('reported_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='log.UserProfile')),
                ('reported_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='log.UserProfile')),
            ],
        ),
    ]
