# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_userprofile_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='u',
        ),
    ]
