# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20180818_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('like_notification', 'like_notification'), ('comment_notification', 'comment_notification'), ('message_notification', 'message_notification'), ('comment_mention_notification', 'comment_mention_notification'), ('post_mention_notification', 'post_mention_notification')], max_length=200),
        ),
    ]
