# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20180818_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
