# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
