# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0012_auto_20180822_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='club',
            field=models.ManyToManyField(blank=True, to='home.Club'),
        ),
    ]
