# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-25 04:36
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0016_auto_20180825_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res-console.cloudinary.com/dtffozvxo/thumbnails/v1/image/upload/v1535141418/ZGVmYXVsdC9EZWZhdWx0X2F2YXRhcg==/grid', max_length=255, verbose_name='image'),
        ),
    ]
