# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 13:10
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_auto_20180825_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/vishal41/image/upload/v1535172707/nctymexu4qkarkzpz1zw.png', max_length=255, verbose_name='image'),
        ),
    ]
