# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-25 17:46
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_auto_20180825_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/vishal41/image/upload/v1535172707/nctymexu4qkarkzpz1zw.png', max_length=255, verbose_name='image'),
        ),
    ]
