# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0018_auto_20180825_1840'),
        ('log', '0018_auto_20180825_2316'),
    ]

    operations = [
    ]
