# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-28 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0019_merge_20180826_0029'),
        ('log', '0019_merge_20180825_2333'),
    ]

    operations = [
    ]
