# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-29 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0020_merge_20180828_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
