# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
