# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170830_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=b'blog/thumbnail-default.jpg', upload_to=b'blog'),
        ),
    ]
