# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='blog/thumbnail-default.jpg', upload_to='blog'),
        ),
    ]
