# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together=set([('title', 'username')]),
        ),
    ]
