# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170909_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='club',
            field=models.CharField(blank=True, choices=[('cs', 'Codeschool'), ('ct', 'Cogitans'), ('dc', 'Droid Club'), ('ec', 'E-Cell'), ('et', 'Electrotech'), ('os', 'OSLC'), ('ru', 'Rendered-USICT'), ('ta', 'Turing A.I.')], max_length=200),
        ),
    ]
