# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180808_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
