# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentupvote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentupvote',
            unique_together=set([('comment', 'username')]),
        ),
    ]
