# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180812_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='reply_for',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.Comments'),
        ),
    ]
