# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170910_0602'),
        ('blog', '0008_auto_20170910_0813'),
    ]

    operations = [
    ]
