# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180829_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='edited',
        ),
    ]
