# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blogpost_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='edited',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.EditHistoryGeneric'),
        ),
    ]
