# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='a', max_length=2024),
        ),
    ]
