# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180620_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=2024, unique=True, verbose_name='slug'),
        ),
    ]
