# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180621_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
