# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='name',
            field=models.CharField(default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
