# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_upvote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
    ]
