# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_auto_20180727_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='name',
        ),
        migrations.AddField(
            model_name='upvote',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_upvotes', to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='upvote',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
