# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-27 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180727_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.AddField(
            model_name='upvote',
            name='title',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='upvote',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
