# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180727_2131'),
        ('blog', '0018_tag'),
    ]

    operations = [
    ]
