# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_merge_20180728_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to=b'blog'),
        ),
    ]
