# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180728_1826'),
        ('blog', '0024_auto_20180728_2214'),
    ]

    operations = [
    ]
