# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-08 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180729_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
