# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='club',
            field=models.CharField(blank=True, choices=[('codeschool', 'Codeschool'), ('cogitans', 'Cogitans'), ('droidclub', 'Droid Club'), ('ecell', 'E-Cell'), ('electrotech', 'Electrotech'), ('oslc', 'OSLC'), ('renderedusict', 'Rendered-USICT'), ('turingai', 'Turing A.I.')], max_length=200),
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default='img/blog/thumbnail-default.jpg', upload_to='events'),
        ),
    ]
