# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170910_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.CharField(default='no', max_length=255),
        ),
    ]
