# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_events_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
