# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20170913_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
