# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20170913_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default='blog/thumbnail-default.jpg', upload_to='events'),
        ),
    ]
