# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_events_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=models.SlugField(max_length=2024, unique=True),
        ),
    ]
