# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-28 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20180621_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(default=b'img/blog/thumbnail-default.jpg', upload_to=b'events'),
        ),
    ]
