# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='image',
            field=models.ImageField(default=b'blog/thumbnail-default.jpg', upload_to=b'latest_posts'),
        ),
    ]
