# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latest', '0002_auto_20180802_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestpost',
            name='image',
            field=models.ImageField(default='blog/thumbnail-default.jpg', upload_to='latest_posts'),
        ),
    ]
