# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
    ]
