# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='captain',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_image',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
