# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170903_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('captain', models.CharField(max_length=255, null=True)),
                ('club_image', models.ImageField(upload_to='logo')),
            ],
        ),
    ]
