# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170905_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='captain',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
