# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='app_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
