# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_app_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('club', models.CharField(choices=[('codeschool', 'Codeschool'), ('cogitans', 'Cogitans'), ('droidclub', 'Droid Club'), ('ecell', 'E-Cell'), ('electrotech', 'Electrotech'), ('oslc', 'OSLC'), ('renderedusict', 'Rendered-USICT'), ('turingai', 'Turing A.I.')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='clubs/team')),
                ('designation', models.CharField(max_length=255)),
                ('facebook', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('club', models.CharField(choices=[('codeschool', 'Codeschool'), ('cogitans', 'Cogitans'), ('droidclub', 'Droid Club'), ('ecell', 'E-Cell'), ('electrotech', 'Electrotech'), ('oslc', 'OSLC'), ('renderedusict', 'Rendered-USICT'), ('turingai', 'Turing A.I.')], max_length=255)),
            ],
        ),
    ]
