# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_info_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='linkedin',
        ),
    ]
