# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170911_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
