# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='clubs/codeschool/team')),
                ('designation', models.CharField(max_length=255)),
                ('facebook', models.URLField(null=True)),
                ('github', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
            ],
        ),
    ]
